rvm:
  - 2.2.2
  - 2.3.0
  - jruby-19mode
  - rbx-2
before_install:
  - gem update --system
  - gem update bundler
  - gem cleanup bundler
install: "bundle install --jobs 8"
script: "bundle exec rake"
gemfile:
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile
matrix:
  fast_finish: true
  allow_failures:
    - rvm: jruby-19mode
      gemfile: gemfiles/5.0.gemfile
    - rvm: rbx-2
      gemfile: gemfiles/5.0.gemfile
branches:
  only:
    - master

sudo: false
cache: bundler
